version: '3.8'

services:
  bankease-backend:
    build: ./Backend
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bankease_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pandi
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - bankease-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=pandi
      - MYSQL_DATABASE=bankease_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bankease-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bankease-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - bankease-backend
    networks:
      - bankease-network

networks:
  bankease-network:
    driver: bridge

volumes:
  db_data:


