# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bankease-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bankease-network

  redis:
    image: redis:7.0-alpine
    container_name: bankease-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - bankease-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: bankease-backend
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SPRING_APP_NAME=${SPRING_APP_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
    depends_on:
      - mysql
      - redis
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - bankease-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bankease-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - bankease-network

volumes:
  mysql_data:
  redis_data:
  backend_uploads:

networks:
  bankease-network:
    driver: bridge
